'use client'

import { useState } from 'react'
import { ArrowRight, Check } from 'lucide-react'

export function AboutPage({ onNavigate }: { onNavigate: (page: string) => void }) {
  const [playing, setPlaying] = useState(false)
  return <>
    <section className="about-hero"><div className="container about-hero-grid"><div><span className="pill">Meet your doctor</span><h1>Care with <em>conviction.</em></h1><p className="lead">Dr. Ibrahim is a family physician and wellness advocate who believes excellent medicine is equal parts expertise, empathy and consistency.</p><div className="about-credentials"><div><strong>15+</strong><span>Years in practice</span></div><div><strong>2,000+</strong><span>Patients supported</span></div><div><strong>4.9</strong><span>Patient rating</span></div></div><button className="btn btn-primary" onClick={() => onNavigate('Appointment')}>Book a consultation <ArrowRight size={16}/></button></div><div className="about-portrait"><img src="https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=85" alt="Dr. Ibrahim, family physician"/><span className="portrait-caption">Dr. Ibrahim<br/><small>MBChB, MRCGP</small></span></div></div></section>
    <section className="section about-story"><div className="container split-grid"><div><span className="pill">His philosophy</span><h2>Better health is built on <em>trust.</em></h2><p className="lead">From your first conversation to every follow-up, Dr. Ibrahim creates space for questions, context and honest decisions. His work combines rigorous clinical reasoning with practical, everyday guidance.</p><p className="muted">He has a special interest in preventive care, metabolic health, skin health and helping busy families make sustainable changes without shame or extremes.</p></div><div className="principles"><div><span>01</span><div><h3>Listen first</h3><p>Understand the person, not just the symptom.</p></div></div><div><span>02</span><div><h3>Explain clearly</h3><p>Make every diagnosis and option easy to understand.</p></div></div><div><span>03</span><div><h3>Plan together</h3><p>Create care plans that fit your real life.</p></div></div></div></div></section>
    <section className="section about-video"><div className="container"><div className="section-heading"><div><span className="pill pill-teal">Inside the clinic</span><h2>A minute with <em>Dr. Ibrahim.</em></h2></div><p className="muted video-heading-copy">Why he chose medicine, what good care means and how to prepare for your first visit.</p></div><div className="video-card" onClick={() => setPlaying(!playing)}><img src="https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1600&q=85" alt="Dr. Ibrahim speaking in the clinic"/><div className="video-shade"/><button className="play-button" aria-label={playing ? 'Pause video' : 'Play video'}>{playing ? 'Ⅱ' : '▶'}</button><div className="video-meta"><span>CLINIC STORIES · 04:32</span><strong>{playing ? 'Now playing: The art of a good consultation' : 'The art of a good consultation'}</strong></div></div></div></section>
    <section className="section about-details"><div className="container details-grid"><div><span className="pill">Experience & training</span><h2>Rooted in <em>evidence.</em></h2><div className="timeline"><div><strong>2019 — Present</strong><span>Founder & Lead Physician · Dr. Ibrahim Clinic</span></div><div><strong>2015 — 2019</strong><span>Senior Family Physician · Accra Medical Centre</span></div><div><strong>2010 — 2015</strong><span>Medical training & clinical practice · Ghana</span></div></div></div><div className="skills-card"><h3>Areas of expertise</h3>{['Preventive & family medicine','Metabolic and lifestyle health','Skin health & aesthetics','Women’s and men’s wellness','Long-term care planning'].map((x, i) => <div className="skill-row" key={x}><span>0{i + 1}</span><strong>{x}</strong><Check size={16}/></div>)}</div></div></section>
    <section className="section about-extra"><div className="container"><div className="section-heading"><div><span className="pill pill-teal">Your care journey</span><h2>What to expect at <em>every step.</em></h2></div><p className="muted">A calm, considered experience from your first message to your long-term follow-up.</p></div><div className="journey-grid"><article><span>01</span><h3>Listen & understand</h3><p>We make room for your story, symptoms, questions and priorities before recommending anything.</p></article><article><span>02</span><h3>Assess & explain</h3><p>Receive clear findings, options and practical guidance without unnecessary jargon.</p></article><article><span>03</span><h3>Plan & follow through</h3><p>Your care plan evolves with you through thoughtful reviews and an accessible care team.</p></article></div></div></section><section className="section faq-section"><div className="container narrow"><span className="pill">Common questions</span><h2>Good care starts with <em>clarity.</em></h2><div className="faq-list"><details open><summary>What should I bring to my first visit?</summary><p>Bring any current medicines, recent reports, questions and a short note about what you would like help with.</p></details><details><summary>Can I book a follow-up online?</summary><p>Yes. Use the appointment flow to choose your service, chamber, date and preferred time.</p></details><details><summary>Do you offer care across multiple chambers?</summary><p>Yes. Our Dhanmondi, Gulshan and Uttara chambers share one connected patient-first care experience.</p></details></div></div></section>
    <section className="cta-section"><div className="container cta-inner"><div><span className="pill pill-teal">Start a conversation</span><h2>Your health deserves<br/><em>your full attention.</em></h2></div><div><p>Come as you are. Leave with clarity, a plan and a doctor who knows your story.</p><button className="btn btn-primary" onClick={() => onNavigate('Appointment')}>Meet with Dr. Ibrahim <ArrowRight size={17}/></button></div></div></section>
  </>
}
