'use client'
import { useState } from 'react'
import { ArrowRight, Check, Clock3, Mail, MapPin, Phone, Send, ShieldCheck, Star, UserRound } from 'lucide-react'

const treatments = [
  ['PRP Therapy','Regenerative support for hair, skin and scalp concerns with a careful, clinician-led plan.','45 min','From $120'],
  ['Psoriasis Treatment','Long-term support for flare management, trigger awareness and confident skin care.','30 min','From $85'],
  ['Vitiligo Treatment','Thoughtful assessment and integrative care for changing pigmentation and skin health.','45 min','From $100'],
  ['IBS & Gut Health','A practical plan for digestion, nutrition, symptoms and the habits that shape daily wellbeing.','60 min','From $110'],
  ['Integrative Medicine','Personalized care that connects symptoms, lifestyle, prevention and evidence-based treatment.','60 min','From $110'],
  ['Preventive Wellness','A complete annual review with screening guidance, labs and a clear next-step plan.','45 min','From $75'],
]
const testimonials=[['“I finally felt listened to. The plan was simple, personal and actually fit my routine.”','Amara Mensah','Verified patient'],['“The clinic team made every step feel calm. My skin has improved and my confidence is back.”','Nadia Owusu','Verified patient'],['“Clear explanations, no pressure, and thoughtful follow-up. I recommend Dr. Ibrahim wholeheartedly.”','Kwame Asante','Verified patient']]
export function ServicesPage({onNavigate}:{onNavigate:(p:string)=>void}){return <main className="page-section services-page"><div className="container"><span className="eyebrow">SPECIALIST CARE, SIMPLIFIED</span><h1>Care for every <em>chapter.</em></h1><p className="lead max-copy">From a first consultation to a long-term wellness plan, Dr. Ibrahim brings specialist knowledge and human attention to the details that matter.</p><div className="service-intro"><div><span className="pill pill-teal">Our promise</span><h2>Clear answers.<br/><em>Confident next steps.</em></h2></div><div className="service-promise"><div><Check size={18}/><span><strong>Personalized plans</strong>Built around your symptoms, goals and real life.</span></div><div><Check size={18}/><span><strong>Evidence-led care</strong>Modern treatment with a grounded, practical approach.</span></div><div><Check size={18}/><span><strong>Ongoing support</strong>Follow-up that keeps your progress moving forward.</span></div></div></div><div className="treatment-grid">{treatments.map((x,i)=><article className="treatment-card" key={x[0]}><span className="treatment-number">0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><div><span><Clock3 size={14}/> {x[2]}</span><strong>{x[3]}</strong></div><button onClick={()=>onNavigate('Appointment')} className="text-link">Book this service <ArrowRight size={15}/></button></article>)}</div><div className="service-bottom"><div><span className="eyebrow">NOT SURE WHERE TO START?</span><h2>We’ll help you find the <em>right path.</em></h2><p className="muted">Book a general consultation and we’ll listen, assess and recommend the most appropriate next step.</p></div><button className="btn btn-primary" onClick={()=>onNavigate('Appointment')}>Start with a consultation <ArrowRight size={16}/></button></div></div></main>}
export function ContactPage({onNavigate}:{onNavigate:(p:string)=>void}){const [sent,setSent]=useState(false);return <main className="page-section contact-page"><div className="container"><div className="contact-hero"><div><span className="eyebrow">WE’RE HERE TO HELP</span><h1>Let’s start a <em>conversation.</em></h1><p className="lead">Have a question about a service, a chamber, or your next visit? Send us a note and our team will get back to you.</p><div className="contact-details"><div><span><Phone size={17}/></span><p><strong>Call the clinic</strong>+880 1719 395 553<br/><small>Daily · 9:00 AM – 10:00 PM</small></p></div><div><span><Mail size={17}/></span><p><strong>Email us</strong>hello@dribrahim.clinic<br/><small>We reply within one working day</small></p></div><div><span><MapPin size={17}/></span><p><strong>Visit Dhanmondi</strong>American Wellness Center<br/><small>House 45, Road 22, Dhaka</small></p></div></div></div><div className="contact-form-card">{sent?<div className="contact-success"><span><Check size={24}/></span><h2>Message received.</h2><p>Thank you. Our care team will be in touch shortly.</p><button className="btn btn-outline" onClick={()=>setSent(false)}>Send another message</button></div>:<><span className="pill pill-teal">Send a message</span><h2>How can we help?</h2><div className="contact-form"><label>Your name<input placeholder="Full name"/></label><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Phone number<input placeholder="+880"/></label><label>Topic<select><option>General enquiry</option><option>Appointment support</option><option>Service question</option><option>Shop order</option></select></label><label className="wide">Your message<textarea placeholder="Tell us a little more..."/></label><button className="btn btn-primary wide" onClick={()=>setSent(true)}>Send enquiry <Send size={15}/></button></div></>}</div></div><div className="contact-map"><div><span className="eyebrow">FIND US EASILY</span><h2>Three chambers.<br/><em>One standard of care.</em></h2><p>Choose the location that works best for you and get directions in one tap.</p><button className="btn btn-outline" onClick={()=>onNavigate('Chambers')}>View chambers & maps <ArrowRight size={15}/></button></div><div className="contact-map-art"><MapPin size={30}/><span>Accra · Dhaka care network</span></div></div></div></main>}
export function ShopReviews(){return <section className="shop-reviews"><div className="container"><div className="section-heading"><div><span className="eyebrow">PATIENT EXPERIENCES</span><h2>Loved by the people we <em>care for.</em></h2></div><div className="review-summary"><strong>4.9</strong><span><span className="stars">★★★★★</span><small>Based on 128 verified reviews</small></span></div></div><div className="testimonial-grid">{testimonials.map(x=><article key={x[1]}><div className="stars">★★★★★</div><p>{x[0]}</p><footer><span className="review-avatar"><UserRound size={15}/></span><span><strong>{x[1]}</strong><small>{x[2]}</small></span><ShieldCheck size={15}/></footer></article>)}</div></div></section>}
export function RatingControl(){const [rating,setRating]=useState(0);return <div className="rating-control"><span>Rate your experience</span>{[1,2,3,4,5].map(n=><button key={n} aria-label={`${n} stars`} onClick={()=>setRating(n)}><Star size={17} fill={n<=rating?'currentColor':'none'}/></button>)}{rating>0&&<small>{rating}/5</small>}</div>}
