'use client'

import { useEffect, useState } from 'react'
import { Download, Globe2, X } from 'lucide-react'
import { jsPDF } from 'jspdf'

export const copy = { en: { choose: 'Choose your language', subtitle: 'You can switch this anytime from the language control.', english: 'English', bangla: 'বাংলা', language: 'Language', invoice: 'Invoice', download: 'Download PDF', close: 'Close', total: 'Total', clinic: 'Dr. Ibrahim Hossain Khan Clinic', generated: 'Generated securely for your records.' }, bn: { choose: 'আপনার ভাষা নির্বাচন করুন', subtitle: 'ভাষা নিয়ন্ত্রণ থেকে যেকোনো সময় পরিবর্তন করতে পারবেন।', english: 'English', bangla: 'বাংলা', language: 'ভাষা', invoice: 'ইনভয়েস', download: 'PDF ডাউনলোড', close: 'বন্ধ করুন', total: 'মোট', clinic: 'ডা. ইব্রাহিম হোসাইন খান ক্লিনিক', generated: 'আপনার রেকর্ডের জন্য নিরাপদে তৈরি করা হয়েছে।' } }

export function LanguageGate({ onChange }: { onChange: (lang: 'en' | 'bn') => void }) { const [open,setOpen]=useState(true); if(!open)return null; return <div className="language-backdrop"><div className="language-card"><button className="language-close" onClick={()=>setOpen(false)} aria-label="Close"><X/></button><span className="language-orb"><Globe2/></span><span className="eyebrow">DR. IBRAHIM CLINIC</span><h2>{copy.en.choose}</h2><p>{copy.en.subtitle}</p><div className="language-options"><button onClick={()=>{onChange('en');setOpen(false)}}><strong>English</strong><small>Continue in English</small></button><button onClick={()=>{onChange('bn');setOpen(false)}}><strong>বাংলা</strong><small>বাংলায় চালিয়ে যান</small></button></div></div></div> }

export function LanguageControl({ lang, onChange }: { lang:'en'|'bn'; onChange:(lang:'en'|'bn')=>void }) { const t=copy[lang]; return <div className="language-hover"><button aria-label={t.language}><Globe2 size={15}/><span>{lang==='en'?'EN':'বাং'}</span></button><div className="language-tooltip"><strong>{t.language}</strong><button onClick={()=>onChange('en')}>English</button><button onClick={()=>onChange('bn')}>বাংলা</button></div></div> }

export function InvoiceButton({ type='appointment', lang='en' }: { type?:'appointment'|'order'; lang?:'en'|'bn' }) { const [open,setOpen]=useState(false); const t=copy[lang]; const id=type==='order'?'DRI-2048':'APT-2026-0618'; const download=()=>{const pdf=new jsPDF();pdf.setTextColor(23,75,120);pdf.setFontSize(20);pdf.text(t.clinic,20,25);pdf.setFontSize(11);pdf.setTextColor(95,117,128);pdf.text(`${t.invoice} #${id}`,20,37);pdf.text(new Date().toLocaleDateString(),150,37);pdf.line(20,45,190,45);pdf.setTextColor(23,75,120);pdf.setFontSize(14);pdf.text(type==='order'?(lang==='bn'?'অর্ডার সারাংশ':'Order summary'):(lang==='bn'?'অ্যাপয়েন্টমেন্ট সারাংশ':'Appointment summary'),20,62);pdf.setFontSize(11);pdf.text(type==='order'?'Wellness essentials':'Specialist consultation',20,78);pdf.text(`${t.total}: $${type==='order'?'68.00':'45.00'}`,20,96);pdf.setTextColor(95,117,128);pdf.text(t.generated,20,125);pdf.save(`${id}.pdf`)}; return <><button className="invoice-button" onClick={()=>setOpen(true)}><Download size={15}/>{t.invoice}</button>{open&&<div className="invoice-backdrop"><div className="invoice-modal"><button className="language-close" onClick={()=>setOpen(false)} aria-label={t.close}><X/></button><span className="eyebrow">{t.invoice}</span><h2>{t.clinic}</h2><p className="invoice-id">#{id} · 18 June 2026</p><div className="invoice-line"><span>{type==='order'?'Wellness essentials':'Specialist consultation'}</span><strong>${type==='order'?'68.00':'45.00'}</strong></div><div className="invoice-total"><span>{t.total}</span><strong>${type==='order'?'68.00':'45.00'}</strong></div><button className="btn btn-primary full" onClick={download}><Download size={16}/>{t.download}</button><p className="invoice-note">{t.generated}</p></div></div>}</> }
