"use client"

import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, HeartPulse, ShieldCheck } from 'lucide-react'

export const serviceDetails = {
  prp: { title:'PRP Therapy', label:'Regenerative care', intro:'A carefully guided platelet-rich plasma treatment designed to support natural healing and renewal.', points:['Personalised consultation and assessment','Clinician-led treatment planning','Clear aftercare and follow-up support'] },
  psoriasis: { title:'Psoriasis Treatment', label:'Dermatology care', intro:'Long-term support for calmer skin, fewer flare-ups, and a treatment plan built around your daily life.', points:['Trigger and symptom review','Evidence-informed treatment options','Ongoing progress reviews'] },
  vitiligo: { title:'Vitiligo Treatment', label:'Skin confidence', intro:'Compassionate, individualised care to help you understand vitiligo and explore suitable treatment pathways.', points:['Detailed skin assessment','Personalised care planning','Support for confidence and wellbeing'] },
  ibs: { title:'IBS & Gut Health', label:'Digestive wellbeing', intro:'Practical, whole-person support for better digestion, energy, and confidence around food.', points:['Lifestyle and symptom mapping','Nutrition-aware guidance','Measured follow-up milestones'] },
  integrative: { title:'Integrative Medicine', label:'Whole-person care', intro:'A connected approach that brings clinical expertise, prevention, lifestyle, and your own goals into one plan.', points:['Whole-person health review','Collaborative care plan','Sustainable habits and check-ins'] },
} as const

export function ServiceDetailPage({ slug, onNavigate }: { slug: keyof typeof serviceDetails; onNavigate: (page:string)=>void }) {
  const service = serviceDetails[slug]
  return <main className="service-detail-page"><section className="service-detail-hero"><div className="container service-detail-grid"><div className="service-detail-copy"><button className="back-link" onClick={()=>onNavigate('Services')}><ArrowLeft size={15}/> Back to services</button><span className="pill pill-teal">{service.label}</span><h1>{service.title} for <em>lasting wellbeing.</em></h1><p className="lead">{service.intro}</p><div className="detail-actions"><button className="btn btn-primary" onClick={()=>onNavigate('Appointment')}>Book a consultation <ArrowRight size={15}/></button><button className="btn btn-outline" onClick={()=>onNavigate('Contact')}>Ask a question</button></div></div><div className="service-detail-art"><HeartPulse size={42}/><span>Thoughtful care</span><small>Designed around you</small></div></div></section><section className="section service-detail-body"><div className="container service-detail-columns"><div><span className="pill">Your care plan</span><h2>Clear steps, <em>kindly delivered.</em></h2><p className="muted detail-intro">Every plan begins with listening. We explain your options clearly, set realistic goals, and stay connected as your needs change.</p><div className="service-point-list">{service.points.map(point=><div key={point}><CheckCircle2 size={18}/><span>{point}</span></div>)}</div></div><aside className="service-info-card"><ShieldCheck size={22}/><h3>What your visit includes</h3><p>Private consultation, clear recommendations, written next steps, and follow-up guidance from our care team.</p><div className="service-info-row"><Clock3 size={16}/><span>Typically 30–45 minutes</span></div><button className="text-link" onClick={()=>onNavigate('Chambers')}>Choose your chamber <ArrowRight size={14}/></button></aside></div></section><section className="section service-faq"><div className="container narrow"><span className="pill pill-sand">Before you book</span><h2>Questions we hear <em>often.</em></h2><div className="faq-list"><details open><summary>Is this service right for me?</summary><p>Your first consultation is designed to understand your needs and recommend the most appropriate path. You do not need to decide before speaking with us.</p></details><details><summary>What happens after my first visit?</summary><p>You will leave with clear next steps and a follow-up plan tailored to your goals.</p></details></div></div></section></main>
}
