export type PageKey =
  | 'Home'
  | 'About'
  | 'Services'
  | 'Gallery'
  | 'Chambers'
  | 'Contact'
  | 'Appointment'
  | 'Checkout'
  | 'Success'
  | 'ServiceDetail';

export interface SeoData {
  title: string;
  description: string;
  keywords: string[];
  canonical: string;
  ogImage?: string;
  structuredData?: Record<string, any>;
}

export const seoData: Record<PageKey, SeoData> = {
  Home: {
    title: 'DR.IBRAHIM HOSSAIN | Board-Certified Dermatologist & Integrative Medicine Specialist',
    description:
      'Expert dermatology, veneral medicine and integrative care by Dr. Ibrahim Hossain Khan. Dhaka-based consultant dermatologist specializing in PRP therapy, psoriasis management, vitiligo treatment, IBS care, hormonal optimization, infertility support and family medicine. Book your consultation today.',
    keywords: [
      'Dr. Ibrahim Hossain',
      'Dr. Ibrahim Hossain Khan',
      'board-certified dermatologist',
      'consultant dermatologist Dhaka',
      'clinical dermatologist Bangladesh',
      'venereologist Dhaka',
      'VD specialist Bangladesh',
      'integrative medicine physician',
      'trichologist Dhaka',
      'aesthetic medicine specialist',
      'hair restoration specialist',
      'PRP therapy Bangladesh',
      'PRP hair restoration Dhaka',
      'psoriasis treatment Bangladesh',
      'psoriasis management Dhaka',
      'vitiligo treatment Bangladesh',
      'IBS treatment Dhaka',
      'gut health specialist',
      'infertility care Bangladesh',
      'hormonal optimization Dhaka',
      'family medicine Dhaka',
      'preventive medicine Bangladesh',
      'holistic medicine Dhaka',
      'wellness clinic Dhaka',
      'medical clinic Bangladesh',
      'Dhaka healthcare',
      'Bangladesh dermatology clinic',
      'skincare specialist Dhaka',
      'hair loss treatment Bangladesh',
      'scalp disorders treatment',
      'pigmentation treatment',
      'acne treatment Dhaka',
      'skin clinic Bangladesh',
      'venereal disease clinic',
      'STD clinic Dhaka',
      'evidence-based dermatology',
      'regenerative medicine Dhaka',
      'lifestyle medicine Bangladesh',
      'nutrition planning Bangladesh',
      'telehealth Bangladesh',
      'clinic Independence Avenue',
      'patient-centered care Dhaka',
      'personalized medicine Bangladesh',
    ],
    canonical: 'https://dribrahimhossain.com',
    ogImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-t0aIFTDc6pB1akFlYbJx4hrSfNncT0.png',
  },
  About: {
    title: 'About Dr. Ibrahim Hossain | Dermatologist & Integrative Medicine Consultant',
    description:
      'Dr. Ibrahim Hossain Khan is a board-certified dermatologist and integrative medicine consultant in Dhaka, Bangladesh. With M.Sc in Skin & VD Integrative Medicine, he provides evidence-led dermatology, regenerative therapies and holistic patient care.',
    keywords: [
      'Dr. Ibrahim Hossain biography',
      'dermatologist Dhaka',
      'skin specialist Bangladesh',
      'VD consultant Dhaka',
      'integrative medicine doctor',
      'clinical dermatologist profile',
      'medical doctor Dhaka',
      'Bangladesh healthcare professional',
      'dermatology credentials',
      'venereologist Dhaka',
      'aesthetic physician Bangladesh',
      'patient-centered physician',
      'holistic health practitioner',
      'preventive medicine specialist',
      'family medicine doctor Dhaka',
    ],
    canonical: 'https://dribrahimhossain.com/about',
    ogImage: '/logo-256.png',
  },
  Services: {
    title: 'Medical Services | Dr. Ibrahim Hossain Khan Clinic',
    description:
      'Comprehensive dermatology and integrative medicine services including PRP therapy, psoriasis management, vitiligo care, IBS treatment, hormonal optimization, infertility support, preventive wellness and family medicine at our Dhaka clinic.',
    keywords: [
      'dermatology services Dhaka',
      'skin care services Bangladesh',
      'PRP therapy Dhaka',
      'psoriasis treatment Bangladesh',
      'vitiligo care Dhaka',
      'IBS treatment Bangladesh',
      'integrative medicine services',
      'hormonal optimization Bangladesh',
      'infertility treatment Dhaka',
      'preventive wellness Bangladesh',
      'family medicine services',
      'hair restoration services',
      'acne treatment Dhaka',
      'pigmentation therapy',
      'scalp disorder treatment',
      'holistic health services',
      'medical clinic services',
      'specialist consultations',
      'evidence-based treatments',
      'personalized care plans',
      'regenerative therapies',
    ],
    canonical: 'https://dribrahimhossain.com/services',
    ogImage: '/logo-256.png',
  },
  Gallery: {
    title: 'Clinic Gallery | Dr. Ibrahim Hossain Khan',
    description:
      'Explore our modern clinic spaces, compassionate care moments and state-of-the-art facilities. See the DR.IBRAHIM HOSSAIN clinic environment designed for your comfort and wellbeing in Dhaka, Bangladesh.',
    keywords: [
      'clinic gallery Dhaka',
      'dermatology clinic photos',
      'medical clinic Bangladesh',
      'healthcare facility Dhaka',
      'clinic interior Bangladesh',
      'doctor office Dhaka',
      'medical practice photos',
      'wellness clinic gallery',
      'patient care moments',
      'clinic environment Bangladesh',
    ],
    canonical: 'https://dribrahimhossain.com/gallery',
    ogImage: '/logo-256.png',
  },
  Chambers: {
    title: 'Clinic Chambers | Dr. Ibrahim Hossain Khan',
    description:
      'Visit our accessible clinic chambers across Dhaka, Bangladesh. Each location offers the same attentive specialist dermatology and integrative medicine care with flexible scheduling, visiting hours and directions.',
    keywords: [
      'clinic locations Dhaka',
      'dermatologist chambers Bangladesh',
      'medical clinic addresses',
      'clinic visiting hours',
      'doctor chambers Dhaka',
      'healthcare locations Bangladesh',
      'clinic directions Dhaka',
      'appointment locations',
      'specialist clinic chambers',
      'Dhaka medical offices',
    ],
    canonical: 'https://dribrahimhossain.com/chambers',
    ogImage: '/logo-256.png',
  },
  Contact: {
    title: 'Contact Us | Dr. Ibrahim Hossain Khan Clinic',
    description:
      'Contact DR.IBRAHIM HOSSAIN clinic in Dhaka for appointments, enquiries and general support. Call +233 30 290 4420, email hello@dribrahim.clinic, or send us a message. We reply within one working day.',
    keywords: [
      'contact dermatologist Dhaka',
      'clinic contact Bangladesh',
      'book appointment Dhaka',
      'doctor phone number',
      'clinic email Bangladesh',
      'medical enquiry Dhaka',
      'healthcare contact',
      'appointment enquiry',
      'clinic support Bangladesh',
      'doctor consultation booking',
    ],
    canonical: 'https://dribrahimhossain.com/contact',
    ogImage: '/logo-256.png',
  },
  Appointment: {
    title: 'Book Appointment | Dr. Ibrahim Hossain Khan',
    description:
      'Book your dermatology or integrative medicine appointment online. Choose your service, chamber, date and time. Flexible scheduling available Monday through Friday at our Dhaka clinic.',
    keywords: [
      'book dermatologist Dhaka',
      'online appointment booking',
      'doctor appointment Bangladesh',
      'schedule consultation Dhaka',
      'clinic booking online',
      'dermatology appointment',
      'medical appointment booking',
      'flexible scheduling Bangladesh',
      'same-day appointment',
      'specialist consultation booking',
    ],
    canonical: 'https://dribrahimhossain.com/appointment',
    ogImage: '/logo-256.png',
  },
  Checkout: {
    title: 'Checkout | Dr. Ibrahim Hossain Khan',
    description:
      'Complete your appointment booking or service order securely. Review your selected service, chamber, date and time before confirming your visit to DR.IBRAHIM HOSSAIN clinic.',
    keywords: [
      'appointment checkout',
      'clinic payment Bangladesh',
      'secure booking Dhaka',
      'medical service checkout',
      'dermatology appointment confirmation',
    ],
    canonical: 'https://dribrahimhossain.com/checkout',
    ogImage: '/logo-256.png',
  },
  Success: {
    title: 'Booking Confirmed | Dr. Ibrahim Hossain Khan',
    description:
      'Your appointment or order with DR.IBRAHIM HOSSAIN has been confirmed. Check your details, prepare for your visit and contact us if you need to reschedule.',
    keywords: [
      'appointment confirmed',
      'booking success Bangladesh',
      'doctor appointment confirmed',
      'clinic booking complete',
      'dermatology visit scheduled',
    ],
    canonical: 'https://dribrahimhossain.com/success',
    ogImage: '/logo-256.png',
  },
  ServiceDetail: {
    title: 'Service Details | Dr. Ibrahim Hossain Khan',
    description:
      'Detailed information about our dermatology and integrative medicine services including treatment plans, pricing, duration and what to expect during your visit.',
    keywords: [
      'service details Dhaka',
      'treatment information Bangladesh',
      'dermatology service details',
      'medical treatment plans',
      'clinic service pricing',
      'what to expect doctor visit',
      'consultation details',
    ],
    canonical: 'https://dribrahimhossain.com/services',
    ogImage: '/logo-256.png',
  },
};

export const serviceDetailSeo: Record<string, SeoData> = {
  preventive: {
    title: 'Preventive Wellness | Dr. Ibrahim Hossain Khan',
    description:
      'Comprehensive preventive wellness plans including annual health reviews, personalized screening guidance, laboratory diagnostics and proactive health management at our Dhaka clinic.',
    keywords: [
      'preventive wellness Bangladesh',
      'annual health checkup Dhaka',
      'health screening Bangladesh',
      'preventive medicine Dhaka',
      'wellness assessment',
      'proactive healthcare',
      'health review Dhaka',
      'preventive care plan',
      'lifestyle medicine Bangladesh',
      'health optimization',
    ],
    canonical: 'https://dribrahimhossain.com/services/preventive-care',
    ogImage: '/logo-256.png',
  },
  'skin-aesthetics': {
    title: 'Skin & Aesthetics | Dr. Ibrahim Hossain Khan',
    description:
      'Advanced dermatology and aesthetic treatments including acne management, scar revision, pigmentation therapy, skin rejuvenation and cosmetic dermatology by a consultant dermatologist in Dhaka.',
    keywords: [
      'skin aesthetics Bangladesh',
      'aesthetic dermatology Dhaka',
      'cosmetic dermatologist',
      'skin rejuvenation Dhaka',
      'acne treatment Bangladesh',
      'scar revision therapy',
      'pigmentation treatment Dhaka',
      'anti-aging treatment Bangladesh',
      'dermatology aesthetics',
      'skin texture improvement',
    ],
    canonical: 'https://dribrahimhossain.com/services/skin-aesthetics',
    ogImage: '/logo-256.png',
  },
  'family-medicine': {
    title: 'Family Medicine | Dr. Ibrahim Hossain Khan',
    description:
      'Comprehensive family medicine services providing continuity of care for every family member. Preventive guidance, chronic disease management and personalized wellness plans in Dhaka, Bangladesh.',
    keywords: [
      'family medicine Dhaka',
      'family doctor Bangladesh',
      'general practice Dhaka',
      'primary care Bangladesh',
      'family health clinic',
      'chronic disease management',
      'preventive family care',
      'family wellness Bangladesh',
      'general physician Dhaka',
      'family healthcare',
    ],
    canonical: 'https://dribrahimhossain.com/services/family-medicine',
    ogImage: '/logo-256.png',
  },
  'prp-therapy': {
    title: 'PRP Therapy | Dr. Ibrahim Hossain Khan',
    description:
      'Platelet-rich plasma (PRP) therapy for hair restoration, skin rejuvenation and scalp disorders. Evidence-led regenerative treatment by a trichologist and dermatologist in Dhaka, Bangladesh.',
    keywords: [
      'PRP therapy Dhaka',
      'PRP hair restoration Bangladesh',
      'platelet rich plasma treatment',
      'hair loss treatment Dhaka',
      'PRP for hair growth',
      'scalp treatment Bangladesh',
      'trichologist Dhaka',
      'hair restoration therapy',
      'regenerative hair treatment',
      'PRP skin rejuvenation',
      'alopecia treatment Bangladesh',
      'hair density improvement',
    ],
    canonical: 'https://dribrahimhossain.com/services/prp-therapy',
    ogImage: '/logo-256.png',
  },
  'psoriasis-treatment': {
    title: 'Psoriasis Treatment | Dr. Ibrahim Hossain Khan',
    description:
      'Long-term psoriasis management with evidence-based treatment plans. Specialized care for psoriasis vulgaris, flare control, trigger management and skin health maintenance in Dhaka, Bangladesh.',
    keywords: [
      'psoriasis treatment Bangladesh',
      'psoriasis management Dhaka',
      'psoriasis specialist',
      'psoriasis care Bangladesh',
      'chronic skin condition',
      'psoriasis flare control',
      'skin disorder treatment',
      'dermatology psoriasis',
      'psoriasis therapy Dhaka',
      'psoriasis long-term care',
    ],
    canonical: 'https://dribrahimhossain.com/services/psoriasis-treatment',
    ogImage: '/logo-256.png',
  },
  'vitiligo-treatment': {
    title: 'Vitiligo Treatment | Dr. Ibrahim Hossain Khan',
    description:
      'Compassionate vitiligo care with personalized treatment pathways, skin assessment and integrative approaches to support repigmentation and skin health confidence in Dhaka, Bangladesh.',
    keywords: [
      'vitiligo treatment Bangladesh',
      'vitiligo care Dhaka',
      'vitiligo specialist',
      'pigmentation disorder treatment',
      'skin depigmentation therapy',
      'vitiligo management',
      'dermatology vitiligo',
      'vitiligo assessment Dhaka',
      'skin pigment treatment',
      'vitiligo confidence care',
    ],
    canonical: 'https://dribrahimhossain.com/services/vitiligo-treatment',
    ogImage: '/logo-256.png',
  },
  'ibs-gut-health': {
    title: 'IBS & Gut Health | Dr. Ibrahim Hossain Khan',
    description:
      'Comprehensive IBS and gut health management with lifestyle mapping, nutrition-aware guidance and measured follow-up milestones. Integrative approach to digestive wellbeing in Dhaka, Bangladesh.',
    keywords: [
      'IBS treatment Bangladesh',
      'gut health specialist Dhaka',
      'digestive health Bangladesh',
      'IBS management Dhaka',
      'gut health doctor',
      'digestive disorder treatment',
      'integrative gut health',
      'IBS care Dhaka',
      'nutrition guidance Bangladesh',
      'digestive wellbeing',
      'functional gut disorder',
      'lifestyle gut health',
    ],
    canonical: 'https://dribrahimhossain.com/services/ibs-gut-health',
    ogImage: '/logo-256.png',
  },
  'integrative-medicine': {
    title: 'Integrative Medicine | Dr. Ibrahim Hossain Khan',
    description:
      'Personalized integrative medicine combining conventional treatments with evidence-based complementary therapies. Whole-person care plans connecting symptoms, lifestyle, prevention and treatment in Dhaka.',
    keywords: [
      'integrative medicine Bangladesh',
      'integrative medicine Dhaka',
      'holistic medicine Bangladesh',
      'functional medicine Dhaka',
      'whole-person care',
      'integrative physician',
      'complementary medicine Bangladesh',
      'evidence-based integrative care',
      'lifestyle medicine Dhaka',
      'preventive medicine Bangladesh',
      'personalized medicine',
      'integrative health clinic',
    ],
    canonical: 'https://dribrahimhossain.com/services/integrative-medicine',
    ogImage: '/logo-256.png',
  },
  'preventive-wellness': {
    title: 'Preventive Wellness | Dr. Ibrahim Hossain Khan',
    description:
      'Complete annual wellness review with screening guidance, laboratory diagnostics and clear next-step plans. Proactive preventive medicine and health optimization in Dhaka, Bangladesh.',
    keywords: [
      'preventive wellness Bangladesh',
      'annual wellness checkup',
      'health screening Dhaka',
      'wellness assessment Bangladesh',
      'preventive health plan',
      'annual medical review',
      'proactive healthcare Dhaka',
      'wellness optimization',
      'health maintenance Bangladesh',
      'screening program Dhaka',
    ],
    canonical: 'https://dribrahimhossain.com/services/preventive-wellness',
    ogImage: '/logo-256.png',
  },
};
