export type PageKey =
  | 'Home'
  | 'About'
  | 'Services'
  | 'Gallery'
  | 'Chambers'
  | 'Contact'
  | 'Appointment'
  | 'Checkout'
  | 'Success'
  | 'ServiceDetail';

export interface SeoData {
  title: string;
  description: string;
  keywords: string[];
  canonical: string;
  ogImage?: string;
  structuredData?: Record<string, any>;
}

export const seoData: Record<PageKey, SeoData> = {
  Home: {
    title: 'DR.IBRAHIM HOSSAIN | Board-Certified Dermatologist & Integrative Medicine Specialist',
    description:
      'Expert dermatology, veneral medicine and integrative care by Dr. Ibrahim Hossain Khan. Accra-based consultant dermatologist specializing in PRP therapy, psoriasis management, vitiligo treatment, IBS care, hormonal optimization, infertility support and family medicine. Book your consultation today.',
    keywords: [
      'Dr. Ibrahim Hossain',
      'Dr. Ibrahim Hossain Khan',
      'board-certified dermatologist',
      'consultant dermatologist Accra',
      'clinical dermatologist Ghana',
      'venereologist Accra',
      'VD specialist Ghana',
      'integrative medicine physician',
      'trichologist Accra',
      'aesthetic medicine specialist',
      'hair restoration specialist',
      'PRP therapy Ghana',
      'PRP hair restoration Accra',
      'psoriasis treatment Ghana',
      'psoriasis management Accra',
      'vitiligo treatment Ghana',
      'IBS treatment Accra',
      'gut health specialist',
      'infertility care Ghana',
      'hormonal optimization Accra',
      'family medicine Accra',
      'preventive medicine Ghana',
      'holistic medicine Accra',
      'wellness clinic Accra',
      'medical clinic Ghana',
      'Accra healthcare',
      'Ghana dermatology clinic',
      'skincare specialist Accra',
      'hair loss treatment Ghana',
      'scalp disorders treatment',
      'pigmentation treatment',
      'acne treatment Accra',
      'skin clinic Ghana',
      'venereal disease clinic',
      'STD clinic Accra',
      'evidence-based dermatology',
      'regenerative medicine Accra',
      'lifestyle medicine Ghana',
      'nutrition planning Ghana',
      'telehealth Ghana',
      'clinic Independence Avenue',
      'patient-centered care Accra',
      'personalized medicine Ghana',
    ],
    canonical: 'https://dribrahimhossain.com',
    ogImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-t0aIFTDc6pB1akFlYbJx4hrSfNncT0.png',
  },
  About: {
    title: 'About Dr. Ibrahim Hossain | Dermatologist & Integrative Medicine Consultant',
    description:
      'Dr. Ibrahim Hossain Khan is a board-certified dermatologist and integrative medicine consultant in Accra, Ghana. With M.Sc in Skin & VD Integrative Medicine, he provides evidence-led dermatology, regenerative therapies and holistic patient care.',
    keywords: [
      'Dr. Ibrahim Hossain biography',
      'dermatologist Accra',
      'skin specialist Ghana',
      'VD consultant Accra',
      'integrative medicine doctor',
      'clinical dermatologist profile',
      'medical doctor Accra',
      'Ghana healthcare professional',
      'dermatology credentials',
      'venereologist Accra',
      'aesthetic physician Ghana',
      'patient-centered physician',
      'holistic health practitioner',
      'preventive medicine specialist',
      'family medicine doctor Accra',
    ],
    canonical: 'https://dribrahimhossain.com/about',
    ogImage: '/logo-256.png',
  },
  Services: {
    title: 'Medical Services | Dr. Ibrahim Hossain Khan Clinic',
    description:
      'Comprehensive dermatology and integrative medicine services including PRP therapy, psoriasis management, vitiligo care, IBS treatment, hormonal optimization, infertility support, preventive wellness and family medicine at our Accra clinic.',
    keywords: [
      'dermatology services Accra',
      'skin care services Ghana',
      'PRP therapy Accra',
      'psoriasis treatment Ghana',
      'vitiligo care Accra',
      'IBS treatment Ghana',
      'integrative medicine services',
      'hormonal optimization Ghana',
      'infertility treatment Accra',
      'preventive wellness Ghana',
      'family medicine services',
      'hair restoration services',
      'acne treatment Accra',
      'pigmentation therapy',
      'scalp disorder treatment',
      'holistic health services',
      'medical clinic services',
      'specialist consultations',
      'evidence-based treatments',
      'personalized care plans',
      'regenerative therapies',
    ],
    canonical: 'https://dribrahimhossain.com/services',
    ogImage: '/logo-256.png',
  },
  Gallery: {
    title: 'Clinic Gallery | Dr. Ibrahim Hossain Khan',
    description:
      'Explore our modern clinic spaces, compassionate care moments and state-of-the-art facilities. See the DR.IBRAHIM HOSSAIN clinic environment designed for your comfort and wellbeing in Accra, Ghana.',
    keywords: [
      'clinic gallery Accra',
      'dermatology clinic photos',
      'medical clinic Ghana',
      'healthcare facility Accra',
      'clinic interior Ghana',
      'doctor office Accra',
      'medical practice photos',
      'wellness clinic gallery',
      'patient care moments',
      'clinic environment Ghana',
    ],
    canonical: 'https://dribrahimhossain.com/gallery',
    ogImage: '/logo-256.png',
  },
  Chambers: {
    title: 'Clinic Chambers | Dr. Ibrahim Hossain Khan',
    description:
      'Visit our accessible clinic chambers across Accra, Ghana. Each location offers the same attentive specialist dermatology and integrative medicine care with flexible scheduling, visiting hours and directions.',
    keywords: [
      'clinic locations Accra',
      'dermatologist chambers Ghana',
      'medical clinic addresses',
      'clinic visiting hours',
      'doctor chambers Accra',
      'healthcare locations Ghana',
      'clinic directions Accra',
      'appointment locations',
      'specialist clinic chambers',
      'Accra medical offices',
    ],
    canonical: 'https://dribrahimhossain.com/chambers',
    ogImage: '/logo-256.png',
  },
  Contact: {
    title: 'Contact Us | Dr. Ibrahim Hossain Khan Clinic',
    description:
      'Contact DR.IBRAHIM HOSSAIN clinic in Accra for appointments, enquiries and general support. Call +233 30 290 4420, email hello@dribrahim.clinic, or send us a message. We reply within one working day.',
    keywords: [
      'contact dermatologist Accra',
      'clinic contact Ghana',
      'book appointment Accra',
      'doctor phone number',
      'clinic email Ghana',
      'medical enquiry Accra',
      'healthcare contact',
      'appointment enquiry',
      'clinic support Ghana',
      'doctor consultation booking',
    ],
    canonical: 'https://dribrahimhossain.com/contact',
    ogImage: '/logo-256.png',
  },
  Appointment: {
    title: 'Book Appointment | Dr. Ibrahim Hossain Khan',
    description:
      'Book your dermatology or integrative medicine appointment online. Choose your service, chamber, date and time. Flexible scheduling available Monday through Friday at our Accra clinic.',
    keywords: [
      'book dermatologist Accra',
      'online appointment booking',
      'doctor appointment Ghana',
      'schedule consultation Accra',
      'clinic booking online',
      'dermatology appointment',
      'medical appointment booking',
      'flexible scheduling Ghana',
      'same-day appointment',
      'specialist consultation booking',
    ],
    canonical: 'https://dribrahimhossain.com/appointment',
    ogImage: '/logo-256.png',
  },
  Checkout: {
    title: 'Checkout | Dr. Ibrahim Hossain Khan',
    description:
      'Complete your appointment booking or service order securely. Review your selected service, chamber, date and time before confirming your visit to DR.IBRAHIM HOSSAIN clinic.',
    keywords: [
      'appointment checkout',
      'clinic payment Ghana',
      'secure booking Accra',
      'medical service checkout',
      'dermatology appointment confirmation',
    ],
    canonical: 'https://dribrahimhossain.com/checkout',
    ogImage: '/logo-256.png',
  },
  Success: {
    title: 'Booking Confirmed | Dr. Ibrahim Hossain Khan',
    description:
      'Your appointment or order with DR.IBRAHIM HOSSAIN has been confirmed. Check your details, prepare for your visit and contact us if you need to reschedule.',
    keywords: [
      'appointment confirmed',
      'booking success Ghana',
      'doctor appointment confirmed',
      'clinic booking complete',
      'dermatology visit scheduled',
    ],
    canonical: 'https://dribrahimhossain.com/success',
    ogImage: '/logo-256.png',
  },
  ServiceDetail: {
    title: 'Service Details | Dr. Ibrahim Hossain Khan',
    description:
      'Detailed information about our dermatology and integrative medicine services including treatment plans, pricing, duration and what to expect during your visit.',
    keywords: [
      'service details Accra',
      'treatment information Ghana',
      'dermatology service details',
      'medical treatment plans',
      'clinic service pricing',
      'what to expect doctor visit',
      'consultation details',
    ],
    canonical: 'https://dribrahimhossain.com/services',
    ogImage: '/logo-256.png',
  },
};

export const serviceDetailSeo: Record<string, SeoData> = {
  preventive: {
    title: 'Preventive Wellness | Dr. Ibrahim Hossain Khan',
    description:
      'Comprehensive preventive wellness plans including annual health reviews, personalized screening guidance, laboratory diagnostics and proactive health management at our Accra clinic.',
    keywords: [
      'preventive wellness Ghana',
      'annual health checkup Accra',
      'health screening Ghana',
      'preventive medicine Accra',
      'wellness assessment',
      'proactive healthcare',
      'health review Accra',
      'preventive care plan',
      'lifestyle medicine Ghana',
      'health optimization',
    ],
    canonical: 'https://dribrahimhossain.com/services/preventive-care',
    ogImage: '/logo-256.png',
  },
  'skin-aesthetics': {
    title: 'Skin & Aesthetics | Dr. Ibrahim Hossain Khan',
    description:
      'Advanced dermatology and aesthetic treatments including acne management, scar revision, pigmentation therapy, skin rejuvenation and cosmetic dermatology by a consultant dermatologist in Accra.',
    keywords: [
      'skin aesthetics Ghana',
      'aesthetic dermatology Accra',
      'cosmetic dermatologist',
      'skin rejuvenation Accra',
      'acne treatment Ghana',
      'scar revision therapy',
      'pigmentation treatment Accra',
      'anti-aging treatment Ghana',
      'dermatology aesthetics',
      'skin texture improvement',
    ],
    canonical: 'https://dribrahimhossain.com/services/skin-aesthetics',
    ogImage: '/logo-256.png',
  },
  'family-medicine': {
    title: 'Family Medicine | Dr. Ibrahim Hossain Khan',
    description:
      'Comprehensive family medicine services providing continuity of care for every family member. Preventive guidance, chronic disease management and personalized wellness plans in Accra, Ghana.',
    keywords: [
      'family medicine Accra',
      'family doctor Ghana',
      'general practice Accra',
      'primary care Ghana',
      'family health clinic',
      'chronic disease management',
      'preventive family care',
      'family wellness Ghana',
      'general physician Accra',
      'family healthcare',
    ],
    canonical: 'https://dribrahimhossain.com/services/family-medicine',
    ogImage: '/logo-256.png',
  },
  'prp-therapy': {
    title: 'PRP Therapy | Dr. Ibrahim Hossain Khan',
    description:
      'Platelet-rich plasma (PRP) therapy for hair restoration, skin rejuvenation and scalp disorders. Evidence-led regenerative treatment by a trichologist and dermatologist in Accra, Ghana.',
    keywords: [
      'PRP therapy Accra',
      'PRP hair restoration Ghana',
      'platelet rich plasma treatment',
      'hair loss treatment Accra',
      'PRP for hair growth',
      'scalp treatment Ghana',
      'trichologist Accra',
      'hair restoration therapy',
      'regenerative hair treatment',
      'PRP skin rejuvenation',
      'alopecia treatment Ghana',
      'hair density improvement',
    ],
    canonical: 'https://dribrahimhossain.com/services/prp-therapy',
    ogImage: '/logo-256.png',
  },
  'psoriasis-treatment': {
    title: 'Psoriasis Treatment | Dr. Ibrahim Hossain Khan',
    description:
      'Long-term psoriasis management with evidence-based treatment plans. Specialized care for psoriasis vulgaris, flare control, trigger management and skin health maintenance in Accra, Ghana.',
    keywords: [
      'psoriasis treatment Ghana',
      'psoriasis management Accra',
      'psoriasis specialist',
      'psoriasis care Ghana',
      'chronic skin condition',
      'psoriasis flare control',
      'skin disorder treatment',
      'dermatology psoriasis',
      'psoriasis therapy Accra',
      'psoriasis long-term care',
    ],
    canonical: 'https://dribrahimhossain.com/services/psoriasis-treatment',
    ogImage: '/logo-256.png',
  },
  'vitiligo-treatment': {
    title: 'Vitiligo Treatment | Dr. Ibrahim Hossain Khan',
    description:
      'Compassionate vitiligo care with personalized treatment pathways, skin assessment and integrative approaches to support repigmentation and skin health confidence in Accra, Ghana.',
    keywords: [
      'vitiligo treatment Ghana',
      'vitiligo care Accra',
      'vitiligo specialist',
      'pigmentation disorder treatment',
      'skin depigmentation therapy',
      'vitiligo management',
      'dermatology vitiligo',
      'vitiligo assessment Accra',
      'skin pigment treatment',
      'vitiligo confidence care',
    ],
    canonical: 'https://dribrahimhossain.com/services/vitiligo-treatment',
    ogImage: '/logo-256.png',
  },
  'ibs-gut-health': {
    title: 'IBS & Gut Health | Dr. Ibrahim Hossain Khan',
    description:
      'Comprehensive IBS and gut health management with lifestyle mapping, nutrition-aware guidance and measured follow-up milestones. Integrative approach to digestive wellbeing in Accra, Ghana.',
    keywords: [
      'IBS treatment Ghana',
      'gut health specialist Accra',
      'digestive health Ghana',
      'IBS management Accra',
      'gut health doctor',
      'digestive disorder treatment',
      'integrative gut health',
      'IBS care Accra',
      'nutrition guidance Ghana',
      'digestive wellbeing',
      'functional gut disorder',
      'lifestyle gut health',
    ],
    canonical: 'https://dribrahimhossain.com/services/ibs-gut-health',
    ogImage: '/logo-256.png',
  },
  'integrative-medicine': {
    title: 'Integrative Medicine | Dr. Ibrahim Hossain Khan',
    description:
      'Personalized integrative medicine combining conventional treatments with evidence-based complementary therapies. Whole-person care plans connecting symptoms, lifestyle, prevention and treatment in Accra.',
    keywords: [
      'integrative medicine Ghana',
      'integrative medicine Accra',
      'holistic medicine Ghana',
      'functional medicine Accra',
      'whole-person care',
      'integrative physician',
      'complementary medicine Ghana',
      'evidence-based integrative care',
      'lifestyle medicine Accra',
      'preventive medicine Ghana',
      'personalized medicine',
      'integrative health clinic',
    ],
    canonical: 'https://dribrahimhossain.com/services/integrative-medicine',
    ogImage: '/logo-256.png',
  },
  'preventive-wellness': {
    title: 'Preventive Wellness | Dr. Ibrahim Hossain Khan',
    description:
      'Complete annual wellness review with screening guidance, laboratory diagnostics and clear next-step plans. Proactive preventive medicine and health optimization in Accra, Ghana.',
    keywords: [
      'preventive wellness Ghana',
      'annual wellness checkup',
      'health screening Accra',
      'wellness assessment Ghana',
      'preventive health plan',
      'annual medical review',
      'proactive healthcare Accra',
      'wellness optimization',
      'health maintenance Ghana',
      'screening program Accra',
    ],
    canonical: 'https://dribrahimhossain.com/services/preventive-wellness',
    ogImage: '/logo-256.png',
  },
};
