'use client'

import { useMemo, useState } from 'react'
import { Check, FileText, Plus, Printer, Search, Trash2 } from 'lucide-react'
import type { AdminData, Patient } from '../../lib/admin-data'

export function PrescriptionsView({ data, copy, onLog, toast }: { data: AdminData; copy: any; onLog: (u: string, a: string, t: string) => void; toast: any }) {
  const [query, setQuery] = useState('')
  const [selectedId, setSelectedId] = useState(data.patients[0]?.id || '')
  const [medicines, setMedicines] = useState([{ name: '', dose: '', frequency: 'Once daily', duration: '7 days', instructions: '' }])
  const selected = data.patients.find((patient: Patient) => patient.id === selectedId) || data.patients[0]
  const patients = useMemo(() => data.patients.filter((patient: Patient) => patient.name.toLowerCase().includes(query.toLowerCase()) || patient.id.toLowerCase().includes(query.toLowerCase())), [data.patients, query])
  const addMedicine = () => setMedicines((items) => [...items, { name: '', dose: '', frequency: 'Once daily', duration: '7 days', instructions: '' }])
  const updateMedicine = (index: number, key: string, value: string) => setMedicines((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item))
  const save = () => { if (!selected || medicines.some((item) => !item.name.trim())) { toast.show?.('Select a patient and add a medicine name'); return }; onLog('Dr. Ibrahim', 'created', `Prescription for ${selected.name}`); toast.show?.('Prescription saved securely') }
  return <div className="rx-workspace">
    <div className="rx-heading"><div><span className="pro-kicker">PRESCRIPTION CENTER</span><h1>Prescriptions</h1><p>Create, review and print clear medication plans for every patient.</p></div><div className="rx-actions"><button className="pro-outline btn-pro" onClick={() => window.print()}><Printer size={15}/> Print</button><button className="pro-primary btn-pro shadow-glow-teal" onClick={save}><Check size={15}/> Save prescription</button></div></div>
    <div className="rx-layout">
      <aside className="pro-panel rx-patients"><div className="pro-panel-head"><div><span className="pro-kicker">PATIENTS</span><h2>Select patient</h2></div><span className="rx-count">{patients.length}</span></div><div className="pro-search rx-search"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search patients" /></div><div className="rx-patient-list">{patients.map((patient: Patient) => <button key={patient.id} className={`rx-patient ${patient.id === selected?.id ? 'active' : ''}`} onClick={() => setSelectedId(patient.id)}><span className="rx-avatar">{patient.name.split(' ').map((name) => name[0]).join('')}</span><span><strong>{patient.name}</strong><small>{patient.id} · {patient.conditions[0] || 'General consultation'}</small></span></button>)}</div></aside>
      <section className="pro-panel rx-form"><div className="pro-panel-head"><div><span className="pro-kicker">NEW PRESCRIPTION</span><h2>{selected?.name || 'Choose a patient'}</h2><small className="muted-light">{selected?.id} · {selected?.allergies.length ? `Allergy: ${selected.allergies.join(', ')}` : 'No recorded allergies'}</small></div><FileText size={24} className="rx-icon"/></div><div className="rx-fields"><label>Visit date<input type="date" defaultValue="2026-06-18" /></label><label>Diagnosis / reason<input placeholder="e.g. Skin flare review" /></label></div><div className="rx-med-header"><h3>Medication plan</h3><button className="pro-text-link" onClick={addMedicine}><Plus size={14}/> Add medicine</button></div>{medicines.map((medicine, index) => <div className="rx-med-row" key={index}><div className="rx-med-number">{String(index + 1).padStart(2, '0')}</div><label>Medicine<input value={medicine.name} onChange={(event) => updateMedicine(index, 'name', event.target.value)} placeholder="Medicine name" /></label><label>Dose<input value={medicine.dose} onChange={(event) => updateMedicine(index, 'dose', event.target.value)} placeholder="500 mg" /></label><label>Frequency<select value={medicine.frequency} onChange={(event) => updateMedicine(index, 'frequency', event.target.value)}><option>Once daily</option><option>Twice daily</option><option>Three times daily</option><option>As needed</option></select></label><label>Duration<input value={medicine.duration} onChange={(event) => updateMedicine(index, 'duration', event.target.value)} placeholder="7 days" /></label>{medicines.length > 1 && <button className="rx-remove" aria-label="Remove medicine" onClick={() => setMedicines((items) => items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={15}/></button>}<label className="rx-instructions">Instructions<input value={medicine.instructions} onChange={(event) => updateMedicine(index, 'instructions', event.target.value)} placeholder="After meals, with water" /></label></div>)}<div className="rx-note"><FileText size={15}/><label>Doctor notes<textarea placeholder="Add follow-up guidance, precautions or patient instructions..." /></label></div></section>
    </div>
  </div>
}
